# Generated by Django 3.1.3 on 2020-11-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_comment'),
        ('rareapi', '0003_auto_20201118_1942'),
    ]

    operations = [
    ]
