# Generated by Django 3.1.3 on 2020-11-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20201110_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rareapi.rareuser'),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='bio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.CharField(max_length=100),
        ),
    ]
